### ISSUE TITLE
Useless library

### ISSUE THREAD

**Issue by carp3** [Enderer/sixteensegment#1]
This library is useless.
nothing works. 

You wasted an hour of my time
please remove it from internet.

**Comment by Enderer** [comment]
Sorry you had trouble getting this to work. Maybe looking at the working example would help you out.

http://codepen.io/anon/pen/pKjmJ

**Comment by Mark-Mark** [comment]
I assume he was like me, tried the example and it failed. I dug and found the two errors I posted in the issue I opened and closed.
