### ISSUE TITLE
Not sure what is going on...

### ISSUE THREAD

**Issue by Mark-Mark** [Enderer/sixteensegment#2]
Hello,

Thanks for creating and publishing your code. 

HTML/scripting/etc. is not my primary area but, I normally can muddle through.

I am following the example on the main page and get an error and I am unable to determine the cause. I assume it is something silly I have missed.

The error is:
SCRIPT5022: Invalid element count: [object HTMLCanvasElement]
File: segment.min.js, Line: 1, Column: 158 and it occurs in segment.min.js

`function ElementArray(b){this.SetCount(b||0)}ElementArray.prototype.NullMask=16;ElementArray.prototype.SetCount=function(b){var d=parseInt(b,10);if(isNaN(d))throw"Invalid element count: "+b;this.Elements=[d];for(b=0;b<d;b++)this.Elements[b]=0};`

Here is the test page:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Sixteen Segment Display - Demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <script src="jquery-1.9.1.min.js"></script>
    <script src="segment.min.js"></script>
    <canvas id='c' width='600' height='250'> </canvas>
</head>

<body>

<script>
 var canvas = document.getElementById('c');
 var segment16 = new SixteenSegment(canvas, 6);
 segment16.DisplayText('Hello World');
</script>

</body>
</html>
```

Ideas?

Thanks.

Mark

**Comment by Mark-Mark** [comment]
OK I found the problems. 
The example is wrong.

`var segment16 = new SixteenSegment(canvas, 6);`

The canvas and 6 are backwards.
`var segment16 = new SixteenSegment(6, canvas);`

There is a typo in the source code.

`segment16.DisplayText('Hello World');`

`segment16.DispayText('Hello World');`

This worked:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Sixteen Segment Display - Demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <script src="segment.min.js"></script>
    <canvas id="c" style="position:fixed; left:100px; top:100px; width:300px; height:100px; background-color:#000"> </canvas>

    <script>
    var canvas = document.getElementById('c');
    var segment16 = new SixteenSegment(10,canvas);
     segment16.DispayText("HELLO 7890");

   </script>

</head>

<body>
</body>
</html>
```

**Comment by Enderer** [comment]
Glad you found the issue. I'll try to update the documentation.
